### PR TITLE
Performance tweaks

### PR DESCRIPTION
**Pull request by blueyed**
Mainly for https://github.com/yyuu/pyenv/issues/356.

### CODE REVIEW

**Comment by yyuu** [comment]
Pretty cool :+1: Better performance would be really nice.

Although, separating `bash` processes would be better for simplicity even if it's not the best for performance. I'm not sure performance is how much important for `pyenv` since `pyenv` is basically a command-line tool and will be ran only if some python apps are invoked. Most of time would be consumed by application itself.

**Comment by blueyed** [comment]
> pyenv is basically a command-line tool and will be ran only if some python apps are invoked

Yes, but e.g. with Vim etc, `python` might be called several times, and then it adds up - especially with things like version checking during startup etc, which are expected to be really fast.

I guess this should be first discussed / agreed upon for rbenv.
(btw: see #360 for better merging in the future.. :octocat:)

**Comment by blueyed** [comment]
@yyuu 
Performance is merely an issue, if it gets called often, e.g. with Neovim, where the python interpreter is called multiple times during startup.  But also for things like displaying the pyenv/Python version in your prompt etc.

I've forwarded it to rbenv (https://github.com/sstephenson/rbenv/issues/736), and that seemed to trigger the "anyenv" rewrite in Go.. :)

That means that it won't make it into rbenv.

Given the common merge ancestor we now have, do you think it's worthwile for pyenv, until anyenv would/could replace it possibly?

**Comment by yyuu** [comment]
I think we'd be better to wait for/contribute to anyenv. Until then, I want to keep this not merged to avoid unexpected compatibility issues....

**Comment by blueyed** [comment]
Makes sense, closing it for now.

**Pull request closed without merging**
