### PR TITLE
portable-pypy support

### PR DESCRIPTION
**Pull request by olliewalsh**
Issue #326: have this from last year, only tested on debian wheezy.

### CODE REVIEW

**Comment by BengtOFFIS** [comment]
This adds support for pypy2-2.3.1, pypy2-2.4.0, pypy3-2.3.1 and pypy3-2.4.0, which is already worth pulling. However the current PyPy2 release is 2.5.0 so that version would be most useful to have. Also why not support [all past versions of this portable pypy distibution](https://bitbucket.org/squeaky/portable-pypy/downloads)?

Should the portable pypy have its own namespace? That would actually *not* solve the issue I reported in #326. Perhaps the Ubuntu-specific pypy should move to its own namespace, too. So pyenv would install PyPy from source by default, which should always work. If possible, use the precompiled variants.

I already tested the portable distribution under Fedora. I checked out your branch and all versions downloaded and installed as expected. I had to install virtualenvwrapper manually, to avoid error messages when opening a new terminal.

**Comment by yyuu** [comment]
@olliewalsh :+1:

@BengtOFFIS Lack of some versions isn't a problem. Anyone can write patch and send some PRs.

Replace `pypy` namespace by `pypy-portable` would be nice for Linux variants other than Debian/Ubuntu, but it might not be nice for platforms other than Linux such like OS X. Just introducing new namespace of `pypy-portable` would be the simplest way to deal with....

**Comment by yyuu** [comment]
@BengtOFFIS Pushed 292813eca39d3dd18fde2e6c3040071607b25e51 to install `pypy-portable` on unsupported platforms. This might be the best for your needs.

**Comment by olliewalsh** [comment]
> Also why not support all past versions of this portable pypy distibution?

Been months since I looked at this but IIRC the older portable pypy packages did not create the pypy symlink so they would not work with pyenv - this could be fixed up after install I suppose.

**Comment by olliewalsh** [comment]
Closing this PR as it's superceded by 
https://github.com/yyuu/pyenv/commit/292813eca39d3dd18fde2e6c3040071607b25e51

**Comment by yyuu** [comment]
@olliewalsh 292813eca39d3dd18fde2e6c3040071607b25e51 hasn't been merged into master branch yet. Anyway I will merge them later. Thanks for sending PR :octocat:

**Pull request closed without merging**
